Traceback (most recent call last):
  File "/usr/local/lib/sphinxtrain/scripts/0000.g2p_train/evaluate.py", line 111, in <module>
    process_testset( test_file, wordlist, ref_file )
  File "/usr/local/lib/sphinxtrain/scripts/0000.g2p_train/evaluate.py", line 42, in process_testset
    for entry in open(testfile):
IOError: [Errno 2] No such file or directory: '/home/yaroslav/model/g2p/ua.test'
Wed Apr  6 22:31:55 2016
